version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: backend.Dockerfile
    image: vladi_challenge/backend
    working_dir: /opt/challenge
    ports:
      - "8080:8080"

  frontend:
     build:
       context: ./frontend
       dockerfile: frontend.Dockerfile
     image: vladi_challenge/frontend
     working_dir: /opt/challenge_frontend
     ports:
       - "3000:3000"
