version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: backend.Dockerfile
    image: vladi_challenge/backend
    volumes:
      - ./:/opt/challenge:cached
    working_dir: /opt/challenge
    ports:
      - "8080:8080"

  frontend:
       build:
         context: ./frontend
         dockerfile: frontend.Dockerfile
       image: vladi_challenge/frontend
       volumes:
         - ./frontend:/opt/challenge_frontend:cached
       working_dir: /opt/challenge_frontend
       ports:
         - "3000:3000"
